version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      prod-dependencies:
        dependency-type: production
      dev-dependencies:
        dependency-type: development
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns: ["*"]
    labels:
      - dependencies
      - github-actions
